name: Release to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - go-tool/**
#    tags:
#      - "*.*.*"

defaults:
  run:
    working-directory: go-tool

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: 050046987178.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch required Go modules
        run:  go mod download

      - name: Build
        run:  go build -v ./...

      - name: Build and push Docker image
        id:   docker_build
        uses: docker/build-push-action@v3
        with:
          context: go-tool
          push: true
          tags: |
            050046987178.dkr.ecr.us-east-1.amazonaws.com/terraform-cloud-backup:latest
            050046987178.dkr.ecr.us-east-1.amazonaws.com/terraform-cloud-backup:1.0.0
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
